name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on PR merge to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print secrets for testing
        run: |
          # print out secrets for test
          echo "AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'"
          echo "AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'"
          echo "AWS_REGION: ${{secrets.AWS_REGION}} | sed 's/./& /g'"
          echo "ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}} | sed 's/./& /g'"
          echo "AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}} | sed 's/./& /g'"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          # Define the full image name
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"

          # Build the Docker image
          docker build --platform linux/amd64 -t $IMAGE_URI .

          # Push the image to ECR
          docker push $IMAGE_URI

      - name: Update ECS Service to Force Redeployment
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecs update-service --cluster nextjs14-cluster --service nextjs14-service --force-new-deployment --region $AWS_REGION

      - name: Output ECR Image URL
        run: |
          echo "ECR Image URL: $IMAGE_URI"
